config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  resources :categories, except: :show
  resources :products, path: '/'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :restrict_with_exception
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :photo
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale
  def switch_locale(&action)
    I18n.with_locale(locale_from_header, &action)
  end
  private
  def locale_from_header
    request.env['HTTP_ACCEPT_LANGUAGE']&.scan(/^[a-z]{2}/)&.first || I18n.default_locale
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all.order(name: :asc)
  end
  # GET /categories/1 or /categories/1.json

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    category
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_url, notice: t('.created')
      # format.json { render :show, status: :created, location: @category }
    else
      render :new, status: :unprocessable_entity
      # format.json { render json: @category.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    if category.update(category_params)
      redirect_to categories_url, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    category.destroy
    redirect_to categories_url, notice: t('.destroyed'), status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    pp params[:category_id]
    @categories = Category.order(name: :asc).load_async
    @products = Product.with_attached_photo.order(created_at: :desc).load_async
    if params[:category_id]
      @products = Product.where(category_id: params[:category_id])
    end
  end
  def show
    product
  end
  def new
    @product = Product.new
  end
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path, notice: t('.created')
    else
      render :new, status: :unprocessable_entity
    end
  end
  def edit
    product
  end
  def update
    if product.update(product_params)
      redirect_to products_path, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    product.destroy
    redirect_to products_path, notice: t('.destroyed'), status: :see_other
  end
  private
  def product_params
    params.require(:product).permit(:title, :description, :price, :photo, :category_id)
  end
  def product
    @product = Product.find(params[:id])
  end
  def locale_from_header
    request.env['HTTP_ACCEPT_LANGUAGE']&.scan(/^[a-z]{2}/)&.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name: xxx</strong>
    <%= category.name %>
  </p>
  <div class="d-flex flex-row">
    <%= link_to t('.edit'), edit_category_path(category), class: 'btn btn-primary btn-sm mr-2' %>
    <%= link_to t('.delete'), category_path(category), class: 'btn btn-danger btn-sm', data: {
      turbo_method: :delete,
      turbo_confirm: t('common.confirm')
    } %>
  </div>
  <br />
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% @category.errors.full_messages.each do |error| %>
    <%= error %>
    <br />
  <% end %>
  <%# if category.errors.any? %>
<!--    <div style="color: red">-->
<!--      <h2><%#= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>-->

<!--      <ul>-->
        <%# category.errors.each do |error| %>
<!--          <li><%#= error.full_message %></li>-->
        <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h2><%= t('.title') %></h2>
<%= render "form", category: @category %>
<br />
<div>
  <%#= link_to "Show this category", @category %>
  <%= link_to t('common.back'), categories_path %>
</div>

app/views/categories/index.html.erb
<!--<p style="color: green"><%#= notice %></p>-->
<h2><%= t('.title') %></h2>
<%= render partial: 'category', collection: @categories %>
<!--<div id="categories">-->
  <%# @categories.each do |category| %>
    <%#= render category %>
<!--    <p>-->
      <%#= link_to "Show this category", category %>
<!--    </p>-->
  <%# end %>
<!--</div>-->
<%= link_to t('.new'), new_category_path %>

app/views/categories/new.html.erb
<h2><%= t('.title') %></h2>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to t('common.back'), categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Curso</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= turbo_include_tags %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application", "data-turbolinks-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_category.html.erb
<%= category.name %>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
  <% @product.errors.full_messages.each do |error| %>
    <%= error %>
    <br />
  <% end %>
  <br />
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, type: 'text', class: 'form-control', placeholder: t('.title') %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control', placeholder: t('.description') %>
  </div>
  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: 'form-control', placeholder: t('.price') %>
  </div>
  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name, {
      prompt: t('.category_id')
    },
    {
      class: 'custom-select'
    } %>
  </div>
  <div class="form-group">
    <div class="custom-file">
      <%= form.label :photo, class: 'custom-file-label', for: 'customFile' %>
      <%= form.file_field :photo, type: 'file', class: 'custom-file-input', id: 'customFile', placeholder: t('.photo') %>
    </div>
  </div>
  <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/products/_product.html.erb
<div class="mb-5">
  <h2>
    <%= link_to product_path(product.id), class: 'product' do %>
      <%= product.title %>
    <% end %>
  </h2>
  <%= image_tag product.photo, width: 150 if product.photo.attached? %>
  <br />
  <span><%= product.price %></span>
</div>

app/views/products/edit.html.erb
<h2><%= t('.title') %></h2>
<%= render 'form' %>

app/views/products/index.html.erb
<h1>Productos Push</h1>

<% @products.each do |product| %>
  <%= link_to product_path(product.id), class: 'product' do %>
    <h2><%= product.title %></h2>
  <% end %>
  <span><%= product.price %></span>
<% end %>

app/views/products/new.html.erb
<h2><%= t('.title') %></h2>
<%= render 'form' %>

app/views/products/show.html.erb
<h1 class="title"><%= @product.title %></h1>
<%= image_tag @product.photo, width: 150 if @product.photo.attached? %>
<br /><br />
<p class="description"><%= @product.description %></p>
<span class="price"><%= @product.price %></span>
<br /><br />
<div class="d-flex flex-row">
  <%= link_to t('.edit'), edit_product_path(@product), class: 'btn btn-primary mr-2' %>
  <%= link_to t('.delete'), product_path(@product), class: 'btn btn-danger', data: {
    turbo_method: :delete,
    turbo_confirm: t('common.confirm')
  } %>
</div>

app/views/shared/_flash.html.erb
<% if alert  %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if notice  %>
  <div class="alert alert-primary alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<%= link_to products_path do %>
  <h1>Curso de Ruby</h1>
<% end %>
<div class="container">
  <%= link_to t('.add'), new_product_path, class: 'mr-1' %> |
  <%= link_to t('.categories'), categories_url, class: 'ml-1' %>
</div>